# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UNzlylV5ijO-bhUE_CJXGFjr_2qRaFjt
"""

arabic_translation="وتبحث عن الأشخاص الذين يحتاجون إلى مساعدتك، وتجعل حياتهم أفضل"

pip install TTS

from TTS.api import TTS
tts = TTS("tts_models/multilingual/multi-dataset/xtts_v2", gpu=False)

# generate speech by cloning a voice using default settings
tts.tts_to_file(text= arabic_translation,
                file_path="output.wav",
                speaker_wav=["تحفيزي.mp3"],
                language="ar",
                split_sentences=True
                )