# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1a0MWsV80rRux1cZhbxsjR1pU8KHE450w
"""


"""
pip3 install git+https://github.com/openai/whisper.git
#sudo apt update && sudo apt install ffmpeg
pip3 install deep_translator
pip3 install whisper
rm -rf TTS/ # delete repo to be able to reinstall if needed
git clone --branch xtts_demo -q https://github.com/coqui-ai/TTS.git
pip3 install --use-deprecated=legacy-resolver -q -e TTS
pip3 install --use-deprecated=legacy-resolver -q -r TTS/TTS/demos/xtts_ft_demo/requirements.txt
pip3 install -q typing_extensions==4.8 numpy==1.26.2


TTS
ffmpeg
"""

import sys;
import whisper;
import ssl

ssl._create_default_https_context = ssl._create_unverified_context

model = whisper.load_model("base");
result = model.transcribe(sys.argv[1]);
print(result["text"]);
sys.stdout.flush();