# -*- coding: utf-8 -*-
"""
Untitled16.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1a0MWsV80rRux1cZhbxsjR1pU8KHE450w
"""
"""
pip3 install git+https://github.com/openai/whisper.git
sudo apt update && sudo apt install ffmpeg
pip3 install deep_translator
pip3 install whisper
rm -rf TTS/ # delete repo to be able to reinstall if needed
git clone --branch xtts_demo -q https://github.com/coqui-ai/TTS.git
pip3 install --use-deprecated=legacy-resolver -q -e TTS
pip3 install --use-deprecated=legacy-resolver -q -r TTS/TTS/demos/xtts_ft_demo/requirements.txt
pip3 install -q typing_extensions==4.8 numpy==1.26.2
"""


import sys;

from deep_translator import GoogleTranslator

def translate_to_arabic(text):
    translated_text = GoogleTranslator(source='en', target='ar').translate(text)
    return translated_text
arabic_translation = translate_to_arabic("test this one");

print(arabic_translation);
sys.stdout.flush();