# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UNzlylV5ijO-bhUE_CJXGFjr_2qRaFjt
"""

import sys;

#arabic_translation = "هذا نص أطول لتجربة الموديل، لأنه مبدئيا، لا تظهر عليه آثار النضوج"

arabicTextToTranslate = sys.argv[1];


from TTS.api import TTS
tts = TTS("tts_models/multilingual/multi-dataset/xtts_v2", gpu=False)

# generate speech by cloning a voice using default settings
tts.tts_to_file(text= arabicTextToTranslate,
                file_path="output.wav",
                speaker_wav=["models/train.mp3"],
                language="ar",
                split_sentences=True
                )